{
 "title": "Distributed Tracing",
 "description": "Shows high level LLM successes and failures.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      { "id": "2981aa81", "operator": "=", "scope": "span" }
     ],
     "limit": 1000,
     "query": "{name=\"span\"}",
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Total Failed Validations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 1000,
     "query": "{name=\"step\" } | select(span.output.value)",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "One Second Plus Traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "filters": [
      { "id": "16cb2113", "operator": "=", "scope": "span" },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "1m",
       "valueType": "duration"
      },
      {
       "id": "max-duration",
       "operator": "<",
       "tag": "duration",
       "value": "5m",
       "valueType": "duration"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{ resource.service.name = \"user-service\" && duration > 1s }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Guard run duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "filters": [
      { "id": "0b3c1488", "operator": "=", "scope": "span" }
     ],
     "limit": 1000,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Guard Execution Errors",
   "type": "timeseries",
   "description": "These occur when a runtime error is invoked and the Guard is not able to fulfill a request as exepected",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "filters": [
      { "id": "9a2ba9ae", "operator": "=", "scope": "span" },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "error",
       "valueType": "keyword"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "step" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "All Traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "filters": [
      { "id": "16cb2113", "operator": "=", "scope": "span" }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"Archestra Platform API\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}